[project]
name = "mcb-estimation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "affine==2.4.0",
    "asttokens==3.0.0",
    "attrs==25.3.0",
    "branca==0.8.1",
    "certifi==2025.4.26",
    "charset-normalizer==3.4.2",
    "click==8.2.0",
    "click-plugins==1.1.1",
    "cligj==0.7.2",
    "colorama==0.4.6",
    "comm==0.2.2",
    "contextily==1.6.2",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "cykhash==2.0.1",
    "cython==3.1.2",
    "debugpy==1.8.14",
    "decorator==5.2.1",
    "executing==2.2.0",
    "fiona==1.10.1",
    "folium==0.19.7",
    "fonttools==4.58.2",
    "geographiclib==2.0",
    "geopandas==1.0.1",
    "geopy==2.4.1",
    "idna==3.10",
    "ipykernel==6.29.5",
    "ipython==9.2.0",
    "ipython-pygments-lexers==1.1.1",
    "jedi==0.19.2",
    "jenkspy==0.4.1",
    "jinja2==3.1.6",
    "joblib==1.5.0",
    "jupyter-client==8.6.3",
    "jupyter-core==5.7.2",
    "kiwisolver==1.4.8",
    "mapclassify==2.9.0",
    "markupsafe==3.0.2",
    "matplotlib==3.10.3",
    "matplotlib-inline==0.1.7",
    "mercantile==1.2.1",
    "nest-asyncio==1.6.0",
    "networkx==3.4.2",
    "numpy==2.2.6",
    "osmnx==2.0.3",
    "packaging==25.0",
    "pandas==2.2.3",
    "parso==0.8.4",
    "pillow==11.2.1",
    "platformdirs==4.3.8",
    "prompt-toolkit==3.0.51",
    "psutil==7.0.0",
    "pure-eval==0.2.3",
    "pygments==2.19.1",
    "pyogrio==0.11.0",
    "pyparsing==3.2.3",
    "pyproj==3.7.1",
    "pyrobuf==0.9.3",
    "pyrosm==0.6.2",
    "python-dateutil==2.9.0.post0",
    "python-rapidjson==1.20",
    "pytz==2025.2",
    "pywin32==310",
    "pyzmq==26.4.0",
    "rasterio==1.4.3",
    "requests==2.32.3",
    "rtree==1.4.0",
    "scikit-learn==1.6.1",
    "scipy==1.15.3",
    "setuptools==80.9.0",
    "shapely==2.1.0",
    "six==1.17.0",
    "stack-data==0.6.3",
    "threadpoolctl==3.6.0",
    "tornado==6.5",
    "traitlets==5.14.3",
    "typing-extensions==4.13.2",
    "tzdata==2025.2",
    "urllib3==2.4.0",
    "wcwidth==0.2.13",
    "xyzservices==2025.4.0",
]
